# Phase 1 — Data Foundation (Steps 1.1 → 1.3)

**Scope of this notebook**

| Step | Goal | Output |
| --- | --- | --- |
| **1.1** | Load all 14 tables with a CSV-safe parser | `lake.inventory()` — rows, columns, load time per table |
| **1.2** | Profile every column | `docs/data_dictionary.md` (generated) |
| **1.3** | Measure the join graph | integrity %, fan-out, orphans, key-path resolution, ER diagram |
| **+** | Integrate the campaign briefs | structured briefs + RFP requirement checklist |

**How this notebook is built to scale.** The notebook contains *no data logic*. Every
loader, profiler and join check lives in `src/agentiq/data/`, so Steps 1.4–1.9 and
Phases 3–8 import the same code instead of copying cells. Schema knowledge lives in
one declarative place — `src/agentiq/data/catalog.py` — and this notebook's job is to
**test those declarations against the data** and render the evidence.

> Declarations in the catalogue are hypotheses. Where measurement disagrees, the
> catalogue is wrong and must be corrected — never the other way round.

## 0 · Environment

In [1]:
from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd


def _project_root() -> Path:
    """Locate the repository root whether the kernel starts in / or in notebooks/."""
    for candidate in (Path.cwd(), *Path.cwd().parents):
        if (candidate / "src" / "agentiq").is_dir():
            return candidate
    raise FileNotFoundError("Run this notebook from inside the project tree.")


ROOT = _project_root()
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 90)

print(f"python  {sys.version.split()[0]}")
print(f"pandas  {pd.__version__}")
print(f"root    {ROOT}")

python  3.11.9
pandas  2.2.3
root    C:\Users\ValliappanM\Downloads\Hack Days 26

In [2]:
%load_ext autoreload
%autoreload 2

from agentiq.data import (
    CATALOG,
    KEY_PATHS,
    DataLake,
    ProjectPaths,
    briefs_frame,
    check_all_joins,
    columns_frame,
    coverage_frame,
    derive_fields,
    joins_frame,
    load_briefs,
    mermaid_er,
    paths_frame,
    profile_lake,
    render_data_dictionary,
    render_join_section,
    requirements_frame,
    tables_by_layer,
    tables_frame,
    trace_all_paths,
)

PATHS = ProjectPaths(ROOT).ensure_dirs()
PATHS

ProjectPaths(root=C:\Users\ValliappanM\Downloads\Hack Days 26)

## 1.1 · Inventory and load all 14 tables

Every read goes through `pandas.read_csv` with standard quoting — quoted fields
containing commas are expected in this dataset, so nothing is ever split positionally.
Declared categorical, boolean and date columns are typed at read time; the two large
tables (`bookings`, `ridership_actuals`) are mirrored to parquet on first read so every
later notebook reloads them in a fraction of the time.

**Exit criterion:** row count and column list printed for all 14 tables, zero parse errors.

In [3]:
for layer, names in tables_by_layer().items():
    print(f"{layer:>12}  {', '.join(names)}")
print(f"\n{len(CATALOG)} tables declared in the catalogue.")

   geography  cities, zone_demographics, locations
     network  route_stops, route_schedules, ridership_actuals, vehicles
   inventory  screens, dim_slot
     context  points_of_interest, events
  commercial  client_facts, bookings, lost_leads

14 tables declared in the catalogue.

In [4]:
lake = DataLake(PATHS.raw_data, cache_dir=PATHS.cache)

# First call reads every CSV; subsequent calls are memoised.
inventory = lake.inventory()
inventory.drop(columns=["column_names"])

                 table       layer                    file     rows  columns  memory_mb  load_seconds         source
0               cities   geography              cities.csv        3        6       0.00          0.01            csv
1    zone_demographics   geography   zone_demographics.csv       30       15       0.01          0.00            csv
2            locations   geography           locations.csv      910        6       0.30          0.00            csv
3          route_stops     network         route_stops.csv     2436       11       0.83          0.01            csv
4      route_schedules     network     route_schedules.csv    19838        7       5.32          0.02            csv
5    ridership_actuals     network   ridership_actuals.csv  2049632        7     430.54          0.41  parquet-cache
6             vehicles     network            vehicles.csv      854        5       0.17          0.00            csv
7              screens   inventory             screens.csv    11163        7       2.49          0.02            csv
8             dim_slot   inventory            dim_slot.csv        6        5       0.00          0.00            csv
9   points_of_interest     context  points_of_interest.csv     1375       13       0.50          0.01            csv
10              events     context              events.csv      367       14       0.16          0.01            csv
11        client_facts  commercial        client_facts.csv      520       15       0.20          0.01            csv
12            bookings  commercial            bookings.csv   191109       21      75.87          0.12  parquet-cache
13          lost_leads  commercial          lost_leads.csv     1450       24       0.81          0.03            csv

In [5]:
# The full column list per table — the literal 1.1 exit criterion.
for row in inventory.itertuples():
    print(f"\n{row.table}  ({row.rows:,} rows x {row.columns} cols)")
    print(f"  {row.column_names}")

cities  (3 rows x 6 cols)
  city_id, city_name, population, transit_density, market_tier, timezone

zone_demographics  (30 rows x 15 cols)
  zone_id, city_id, zone_name, resident_population, population_density_per_sqkm, median_age, pct_age_under_18, pct_age_18_34, pct_age_35_54, pct_age_55_plus, median_household_income, income_index, pct_bachelor_or_higher, dominant_occupation, daytime_population_multiplier

locations  (910 rows x 6 cols)
  location_id, city_id, name, city_zone, zone_id, location_type

route_stops  (2,436 rows x 11 cols)
  route_id, corridor_id, city_id, route_name, mode, direction, stop_sequence, location_id, is_first_stop, is_last_stop, num_stops

route_schedules  (19,838 rows x 7 cols)
  schedule_id, route_id, corridor_id, direction, day_type, start_time, estimated_ridership

ridership_actuals  (2,049,632 rows x 7 cols)
  schedule_id, route_id, city_id, date, day_of_week, is_holiday, actual_ridership

vehicles  (854 rows x 5 cols)
  vehicle_id, city_id, vehicle_type, corridor_id, screen_count

screens  (11,163 rows x 7 cols)
  screen_id, city_id, screen_type, location_id, vehicle_id, position, screen_size

dim_slot  (6 rows x 5 cols)
  time_block_id, time_block_label, start_hour, end_hour, nearest_daypart

points_of_interest  (1,375 rows x 13 cols)
  poi_id, city_id, city_zone, name, poi_type, scale, est_daily_footfall, anchor_location_id, distance_to_location_km, distance_to_location_mi, is_network_hub, side_of_road, peak_daypart

events  (367 rows x 14 cols)
  event_id, city_id, city_zone, poi_id, anchor_location_id, event_name, event_type, recurrence, start_date, end_date, expected_attendance, attendance_tier, primary_impact_daypart, impact_radius_km

client_facts  (520 rows x 15 cols)
  client_id, company_name, industry, client_tier, home_city_id, active_cities, preferred_geographies, typical_campaign_budget, budget_variance_pct, campaign_frequency, avg_campaign_duration_days, bundle_affinity, negotiation_leverage, relationship_start_date, account_status

bookings  (191,109 rows x 21 cols)
  booking_id, deal_id, client_id, city_id, screen_id, ad_type, industry_vertical, campaign_objective, time_block_id, daypart, slots_booked_per_day, rotation_type, start_date, end_date, duration_days, booked_date, contracted_price_per_slot_per_day, line_item_value, deal_total_value, is_bundle, booking_status

lost_leads  (1,450 rows x 24 cols)
  lead_id, client_id, company_name_raw, industry_vertical, city_id, requested_geography, anchor_screen_id, lead_source, lead_date, sales_stage_reached, lost_date, requested_start_date, requested_duration_days, requested_num_screens, indicated_budget, quoted_price_per_slot_per_day, client_target_price_per_slot_per_day, price_gap_pct, negotiation_rounds, competitor_mentioned, loss_reason, loss_reason_detail, campaign_objective, ad_type

In [6]:
assert len(inventory) == 14, f"expected 14 tables, loaded {len(inventory)}"
assert (inventory["rows"] > 0).all(), "a table loaded zero rows"
assert (inventory["columns"] > 0).all(), "a table loaded zero columns"
print(
    f"STEP 1.1 PASS — {len(inventory)} tables, "
    f"{inventory['rows'].sum():,} rows, "
    f"{inventory['memory_mb'].sum():,.0f} MB resident, "
    f"{inventory['load_seconds'].sum():.1f}s to load."
)

STEP 1.1 PASS — 14 tables, 2,279,693 rows, 517 MB resident, 0.7s to load.

### Peek at every table

Two rows each — enough to sanity-check the typing without dumping 2M rows.

In [7]:
from IPython.display import display

for name in CATALOG:
    print(f"\n=== {name} — {CATALOG[name].grain}")
    display(lake[name].head(2))

=== cities — One row per city in the network.

  city_id       city_name  population transit_density market_tier          timezone
0      LH    Las Hackland     3200000           dense     premium  America/New_York
1     ACS  Accordionshire      850000       sprawling       value   America/Chicago

=== zone_demographics — One row per city zone.

,zone_id,city_id,zone_name,resident_population,population_density_per_sqkm,median_age,pct_age_under_18,pct_age_18_34,pct_age_35_54,pct_age_55_plus,median_household_income,income_index,pct_bachelor_or_higher,dominant_occupation,daytime_population_multiplier
0,LH-ZONE-001,LH,Downtown Core,107560,14480,32.6,6.7,39.0,38.5,15.8,134615,141.7,64.9,white_collar,3.39
1,LH-ZONE-002,LH,Harborfront,344279,7107,44.7,13.9,26.2,30.9,29.0,99465,104.7,43.8,mixed,1.52

=== locations — One row per physical location (stop / station / roadside point).

   location_id city_id                         name      city_zone      zone_id location_type
0  LH-LOC-0120      LH       Grant Rd & Kingsley Rd  Financial Row  LH-ZONE-005      bus_stop
1  LH-LOC-0135      LH  Concourse Ave & Prospect St   East Commons  LH-ZONE-010      bus_stop

=== route_stops — One row per (route, stop_sequence) — a route's ordered stop list.

         route_id corridor_id city_id route_name mode direction  stop_sequence  location_id  is_first_stop  is_last_stop  num_stops
0  LH-RT-B001-OUT  LH-RT-B001      LH   Route B1  bus  outbound              1  LH-LOC-0236           True         False         14
1  LH-RT-B001-OUT  LH-RT-B001      LH   Route B1  bus  outbound              2  LH-LOC-0316          False         False         14

=== route_schedules — One row per scheduled trip (route x day_type x departure time).

     schedule_id        route_id corridor_id direction day_type start_time  estimated_ridership
0  LH-SCH-000001  LH-RT-B001-OUT  LH-RT-B001  outbound  weekday      05:03                   20
1  LH-SCH-000002  LH-RT-B001-OUT  LH-RT-B001  outbound  weekday      05:47                   17

=== ridership_actuals — One row per (scheduled trip, date) with realised ridership.

     schedule_id        route_id city_id       date day_of_week  is_holiday  actual_ridership
0  LH-SCH-000001  LH-RT-B001-OUT      LH 2026-02-19    Thursday       False                21
1  LH-SCH-000001  LH-RT-B001-OUT      LH 2026-02-20      Friday       False                25

=== vehicles — One row per vehicle carrying screens.

     vehicle_id city_id vehicle_type corridor_id  screen_count
0  LH-VEH-00001      LH          bus  LH-RT-B001             3
1  LH-VEH-00002      LH          bus  LH-RT-B001             3

=== screens — One row per physical screen — the unit that is sold.

       screen_id city_id screen_type  location_id vehicle_id position screen_size
0  LH-SCR-000001      LH    bus_stop  LH-LOC-0120        NaN      top           M
1  LH-SCR-000002      LH    bus_stop  LH-LOC-0120        NaN     left           S

=== dim_slot — One row per sellable time block of the day.

   time_block_id time_block_label  start_hour  end_hour nearest_daypart
0              1      00:00-04:00           0         4           night
1              2      04:00-08:00           4         8         morning

=== points_of_interest — One row per POI, already anchored to its nearest location.

,poi_id,city_id,city_zone,name,poi_type,scale,est_daily_footfall,anchor_location_id,distance_to_location_km,distance_to_location_mi,is_network_hub,side_of_road,peak_daypart
0,LH-POI-0001,LH,Financial Row,Financial Row Heritage Museum,museum,flagship,29380,LH-LOC-0120,0.384,0.239,False,far_side,afternoon
1,LH-POI-0002,LH,East Commons,East Commons Mall,shopping_mall,flagship,8525,LH-LOC-0135,0.782,0.486,False,far_side,evening

=== events — One row per event occurrence with its impact window.

,event_id,city_id,city_zone,poi_id,anchor_location_id,event_name,event_type,recurrence,start_date,end_date,expected_attendance,attendance_tier,primary_impact_daypart,impact_radius_km
0,ACS-EVT-00062,ACS,Fallowfield,ACS-POI-0337,ACS-LOC-0004,Neon Nights Concert Series,concert,one_time,2025-08-26,2025-08-26,23290,large,evening,2.34
1,ACS-EVT-00051,ACS,Fallowfield,ACS-POI-0316,ACS-LOC-0120,ACS Food & Music Festival,festival,one_time,2025-08-28,2025-08-28,12524,medium,afternoon,0.85

=== client_facts — One row per client account.

,client_id,company_name,industry,client_tier,home_city_id,active_cities,preferred_geographies,typical_campaign_budget,budget_variance_pct,campaign_frequency,avg_campaign_duration_days,bundle_affinity,negotiation_leverage,relationship_start_date,account_status
0,CLI-00001,Cinema Entertainment,entertainment,local_business,DAT,DAT,DAT:Central Yard,12900.0,0.28,one_off,25,single_screen,low,2021-10-08,active
1,CLI-00002,Care Clinics,healthcare,local_business,DAT,DAT,DAT:Ashford Row,6200.0,0.44,seasonal,8,single_screen,medium,2026-02-10,active

=== bookings — One row per booking line item: a screen x time block held for a date range. Occupancy needs the booking-expansion transform (Step 1.5).

,booking_id,deal_id,client_id,city_id,screen_id,ad_type,industry_vertical,campaign_objective,time_block_id,daypart,slots_booked_per_day,rotation_type,start_date,end_date,duration_days,booked_date,contracted_price_per_slot_per_day,line_item_value,deal_total_value,is_bundle,booking_status
0,DAT-BKG-0000001,DEAL-000001,CLI-00001,DAT,DAT-SCR-002597,Concert Tour Announcement (Frequency),entertainment,frequency,5,evening,1,single_rotation,2026-03-01,2026-03-27,27,2026-02-08,119.26,3220.02,3220.02,False,completed
1,DAT-BKG-0000002,DEAL-000002,CLI-00001,DAT,DAT-SCR-002432,Movie Release Teaser (Awareness),entertainment,awareness,4,afternoon,2,partial_rotation,2025-09-03,2025-10-03,31,2025-08-17,90.70,5623.40,16562.06,True,completed

=== lost_leads — One row per lost lead / failed negotiation.

,lead_id,client_id,company_name_raw,industry_vertical,city_id,requested_geography,anchor_screen_id,lead_source,lead_date,sales_stage_reached,lost_date,requested_start_date,requested_duration_days,requested_num_screens,indicated_budget,quoted_price_per_slot_per_day,client_target_price_per_slot_per_day,price_gap_pct,negotiation_rounds,competitor_mentioned,loss_reason,loss_reason_detail,campaign_objective,ad_type
0,LEAD-000001,CLI-00063,NaN,healthcare,LH,LH:East Commons,LH-SCR-002131,repeat_client_inquiry,2025-10-29,contract_sent,2025-12-23,2026-01-16,87,1,152659.64,81.19,78.10,0.0396,3,True,contract_terms_disagreement,Disagreement over cancellation/make-good terms,conversion,New Clinic Announcement (Conversion)
1,LEAD-000002,CLI-00502,NaN,hospitality,DAT,DAT:Lakeside Loop,DAT-SCR-002830,referral,2026-06-14,negotiating,2026-06-22,2026-07-05,23,9,4111.23,58.38,40.15,0.4540,3,False,price_too_high,Client benchmarked against a cheaper media mix,frequency,Loyalty Membership Drive (Frequency)

## 1.2 · Build the data dictionary

For every table: grain, row count, primary-key uniqueness, duplicate rows. For every
column: dtype, null %, cardinality, min/max (or top-10 values) and a **stated meaning**.

Meanings come from `catalog.py`; any column without one is emitted with `#TODO-semantics`,
which is the checklist that must be empty before Phase 3.

The dictionary is *generated*, so it cannot drift from the data — regenerate with
`python scripts/build_data_dictionary.py`.

In [8]:
profiles = profile_lake(lake)

table_summary = tables_frame(profiles)
table_summary

,table,layer,rows,columns,memory_mb,primary_key,pk_unique,pk_nulls,duplicate_rows,undocumented_columns,grain
0,cities,geography,3,6,0.00,city_id,True,0,0,0,One row per city in the network.
1,zone_demographics,geography,30,15,0.01,zone_id,True,0,0,0,One row per city zone.
2,locations,geography,910,6,0.30,location_id,True,0,0,0,One row per physical location (stop / station / roadside point).
3,route_stops,network,2436,11,0.83,route_id + stop_sequence,True,0,0,0,"One row per (route, stop_sequence) — a route's ordered stop list."
4,route_schedules,network,19838,7,5.32,schedule_id,True,0,0,0,One row per scheduled trip (route x day_type x departure time).
5,ridership_actuals,network,2049632,7,430.54,schedule_id + date,True,0,0,0,"One row per (scheduled trip, date) with realised ridership."
6,vehicles,network,854,5,0.17,vehicle_id,True,0,0,0,One row per vehicle carrying screens.
7,screens,inventory,11163,7,2.49,screen_id,True,0,0,0,One row per physical screen — the unit that is sold.
8,dim_slot,inventory,6,5,0.00,time_block_id,True,0,0,0,One row per sellable time block of the day.
9,points_of_interest,context,1375,13,0.50,poi_id,True,0,0,0,"One row per POI, already anchored to its nearest location."
10,events,context,367,14,0.16,event_id,True,0,0,0,One row per event occurrence with its impact window.
11,client_facts,commercial,520,15,0.20,client_id,True,0,0,0,One row per client account.
12,bookings,commercial,191109,21,75.87,booking_id,True,0,0,0,One row per booking line item: a screen x time block held for a date range. Occupancy ...
13,lost_leads,commercial,1450,24,0.81,lead_id,True,0,0,0,One row per lost lead / failed negotiation.

In [9]:
# Primary keys are *tested*, not trusted.
pk_failures = table_summary[table_summary["pk_unique"] == False]  # noqa: E712
if len(pk_failures):
    display(pk_failures[["table", "primary_key", "rows", "pk_nulls", "duplicate_rows"]])
    print("^ FIX catalog.py: these declared primary keys are not unique.")
else:
    print("All 14 declared primary keys are unique with no nulls in the key.")

All 14 declared primary keys are unique with no nulls in the key.

In [10]:
columns = columns_frame(profiles)
print(f"{len(columns)} columns profiled across {columns['table'].nunique()} tables.")

# Columns most likely to need a handling rule in the Step 1.7 DQ register.
columns[columns["null_pct"] > 0].sort_values("null_pct", ascending=False)[
    ["table", "column", "dtype", "null_pct", "n_unique", "note"]
]

156 columns profiled across 14 tables.

          table                                column     dtype  null_pct  n_unique                                                                                       note
61      screens                            vehicle_id    object    0.7657       854  Set for the 2,615 mobile screens (23.4%), null for static ones. Exactly one of locatio...
134  lost_leads                      company_name_raw    object    0.5566       269  Free-text company name for prospects with no account yet (643 rows); null on the 807 r...
148  lost_leads  client_target_price_per_slot_per_day   float64    0.4759       731  The price the client wanted; null wherever no quote was made or no counter-offer was g...
149  lost_leads                         price_gap_pct   float64    0.4759       713  (quote - client target) / target. The core price-cap calibration signal: the gap at wh...
133  lost_leads                             client_id    object    0.4434       346  Existing account, where the lead came from one. Null on 643 rows — and those are exact...
147  lost_leads         quoted_price_per_slot_per_day   float64    0.3662       889  Our quote. Null for all 531 initial_inquiry leads and only those — the lead died befor...
60      screens                           location_id    object    0.2343       910                            Set for the 8,548 static screens (76.6%), null for mobile ones.
85       events                                poi_id    object    0.2343       147               Host POI where one applies; null for 23% of events (street events, parades).
62      screens                              position  category    0.1254         6  platform / entrance_exit / left / right / top / back. Null on all 1,400 metro_rail_coa...

In [11]:
# Constant columns carry no signal; single-valued keys are candidate join hazards.
constant = columns[(columns["n_unique"] <= 1) & (columns["non_null"] > 0)]
display(constant[["table", "column", "n_unique", "top_values"]])

todo = columns[columns["note"] == "#TODO-semantics"]
print(f"\n{len(todo)} columns still lack a stated meaning (must be 0 before Phase 3):")
for table, group in todo.groupby("table"):
    print(f"  {table}: {', '.join(group['column'])}")

Empty DataFrame
Columns: [table, column, n_unique, top_values]
Index: []

0 columns still lack a stated meaning (must be 0 before Phase 3):

### Categorical vocabularies

These value sets are what Phase 4 must resolve brief language *onto*, and what
`config/taxonomy.yaml` has to enumerate. Read them before inventing any label.

In [12]:
vocab = columns[(columns["kind"] == "categorical") & (columns["n_unique"] <= 30)]
for row in vocab.itertuples():
    print(f"{row.table}.{row.column}  ({row.n_unique})\n    {row.top_values}\n")

cities.city_id  (3)
    LH (1); ACS (1); DAT (1)

cities.city_name  (3)
    Las Hackland (1); Accordionshire (1); DA Town (1)

cities.transit_density  (3)
    dense (1); mixed (1); sprawling (1)

cities.market_tier  (3)
    premium (1); standard (1); value (1)

cities.timezone  (3)
    America/Chicago (1); America/Denver (1); America/New_York (1)

zone_demographics.zone_id  (30)
    LH-ZONE-001 (1); LH-ZONE-002 (1); LH-ZONE-003 (1); LH-ZONE-004 (1); LH-ZONE-005 (1); LH-ZONE-006 (1); LH-ZONE-007 (1); LH-ZONE-008 (1); LH-ZONE-009 (1); LH-ZONE-010 (1)

zone_demographics.city_id  (3)
    LH (10); ACS (10); DAT (10)

zone_demographics.zone_name  (30)
    Downtown Core (1); Harborfront (1); Old Mill District (1); Uptown Crescent (1); Financial Row (1); Cathedral Heights (1); Riverside Junction (1); North Terminus (1); Market Quarter (1); East Commons (1)

zone_demographics.dominant_occupation  (5)
    mixed (14); white_collar (7); blue_collar (3); retail_service (3); student (3)

locations.city_id  (3)
    LH (350); DAT (300); ACS (260)

locations.city_zone  (30)
    Financial Row (36); Old Mill District (36); Harborfront (36); Downtown Core (36); Uptown Crescent (36); East Commons (34); Cathedral Heights (34); North Terminus (34); Market Quarter (34); Riverside Junction (34)

locations.zone_id  (30)
    LH-ZONE-005 (36); LH-ZONE-003 (36); LH-ZONE-002 (36); LH-ZONE-001 (36); LH-ZONE-004 (36); LH-ZONE-010 (34); LH-ZONE-006 (34); LH-ZONE-008 (34); LH-ZONE-009 (34); LH-ZONE-007 (34)

locations.location_type  (2)
    bus_stop (719); metro_station (191)

route_stops.city_id  (3)
    LH (998); DAT (794); ACS (644)

route_stops.mode  (2)
    bus (1,660); metro (776)

route_stops.direction  (2)
    inbound (1,218); outbound (1,218)

route_schedules.direction  (2)
    inbound (9,943); outbound (9,895)

route_schedules.day_type  (2)
    weekday (13,052); weekend (6,786)

ridership_actuals.city_id  (3)
    LH (845,754); DAT (715,078); ACS (488,800)

ridership_actuals.day_of_week  (7)
    Friday (339,352); Monday (339,352); Thursday (339,352); Wednesday (339,352); Tuesday (339,352); Saturday (176,436); Sunday (176,436)

vehicles.city_id  (3)
    LH (370); DAT (284); ACS (200)

vehicles.vehicle_type  (2)
    metro_train (449); bus (405)

screens.city_id  (3)
    LH (6,304); DAT (3,123); ACS (1,736)

screens.screen_type  (4)
    metro_station (6,391); bus_stop (2,157); metro_rail_coach (1,400); bus (1,215)

screens.position  (6)
    platform (5,116); entrance_exit (1,275); right (1,124); left (1,124); top (719); back (405)

screens.screen_size  (3)
    M (4,528); L (3,428); S (3,207)

dim_slot.time_block_label  (6)
    00:00-04:00 (1); 04:00-08:00 (1); 08:00-12:00 (1); 12:00-16:00 (1); 16:00-20:00 (1); 20:00-24:00 (1)

dim_slot.nearest_daypart  (5)
    night (2); afternoon (1); evening (1); midday (1); morning (1)

points_of_interest.city_id  (3)
    LH (591); DAT (447); ACS (337)

points_of_interest.city_zone  (30)
    Downtown Core (81); Central Yard (69); Old Mill District (61); Harborfront (61); Uptown Crescent (59); Financial Row (58); Cathedral Heights (57); Riverside Junction (56); Maple Grove (56); North Terminus (55)

points_of_interest.poi_type  (13)
    shopping_mall (225); grocery_anchor (202); office_park (175); residential_tower (154); entertainment_district (141); government_building (112); hospital (87); corporate_campus (76); university (66); hotel_convention (52)

points_of_interest.scale  (4)
    neighborhood (507); minor (401); major (358); flagship (109)

points_of_interest.side_of_road  (2)
    near_side (728); far_side (647)

points_of_interest.peak_daypart  (5)
    evening (401); afternoon (307); morning (299); midday (245); night (123)

events.city_id  (3)
    LH (157); DAT (119); ACS (91)

events.city_zone  (30)
    Financial Row (50); Fallowfield (46); Central Yard (46); Downtown Core (26); Harrow Point (16); Harborfront (16); Cathedral Heights (15); Maple Grove (13); Kestrel Heights (11); Riverside Junction (11)

events.event_type  (10)
    sports_game (82); concert (70); festival (41); community_fair (33); parade (29); convention (29); trade_show (29); holiday_event (21); political_rally (21); marathon_race (12)

events.recurrence  (3)
    one_time (264); weekly_season (82); annual (21)

events.attendance_tier  (3)
    large (175); medium (175); small (17)

events.primary_impact_daypart  (5)
    evening (129); afternoon (87); midday (65); morning (53); night (33)

client_facts.industry  (13)
    retail (76); entertainment (59); finance (52); cpg (50); auto (46); technology (38); healthcare (37); real_estate (35); hospitality (31); education (30)

client_facts.client_tier  (3)
    local_business (294); regional_chain (149); national_chain (77)

client_facts.home_city_id  (3)
    ACS (179); LH (176); DAT (165)

client_facts.active_cities  (12)
    LH (127); ACS (124); DAT (111); ACS|LH|DAT (24); LH|ACS (22); DAT|LH|ACS (21); DAT|LH (19); ACS|DAT (17); LH|DAT (15); ACS|LH (14)

client_facts.campaign_frequency  (4)
    one_off (178); seasonal (165); quarterly (129); always_on (48)

client_facts.bundle_affinity  (3)
    single_screen (277); moderate_bundle (160); heavy_bundle (83)

client_facts.negotiation_leverage  (3)
    low (262); medium (180); high (78)

client_facts.account_status  (2)
    active (465); lapsed (55)

bookings.city_id  (3)
    LH (119,967); DAT (53,969); ACS (17,173)

bookings.industry_vertical  (13)
    retail (27,914); finance (22,402); technology (18,899); cpg (18,537); entertainment (17,068); auto (16,864); telecom (13,680); real_estate (11,323); education (10,928); healthcare (10,015)

bookings.campaign_objective  (4)
    awareness (75,534); reach (46,104); conversion (36,482); frequency (32,989)

bookings.daypart  (5)
    morning (59,475); evening (47,142); midday (41,340); afternoon (26,082); night (17,070)

bookings.rotation_type  (3)
    partial_rotation (93,532); single_rotation (64,728); full_exclusivity (32,849)

bookings.booking_status  (3)
    completed (111,727); upcoming (49,428); active (29,954)

lost_leads.industry_vertical  (13)
    retail (240); entertainment (132); cpg (127); healthcare (127); auto (125); finance (122); technology (106); hospitality (95); education (94); real_estate (94)

lost_leads.city_id  (3)
    ACS (508); LH (496); DAT (446)

lost_leads.requested_geography  (30)
    LH:Harborfront (86); ACS:Greenhollow (62); DAT:Northbank (60); ACS:Sunridge Acres (58); DAT:Lakeside Loop (55); DAT:Ashford Row (55); LH:Riverside Junction (55); LH:North Terminus (54); ACS:Old Orchard (54); ACS:Maple Grove (53)

lost_leads.lead_source  (6)
    repeat_client_inquiry (500); website_form (250); inbound_call (195); cold_outreach (189); referral (185); trade_show (131)

lost_leads.sales_stage_reached  (5)
    initial_inquiry (531); quote_sent (415); negotiating (281); verbal_agreement (141); contract_sent (82)

lost_leads.loss_reason  (10)
    price_too_high (305); no_response_ghosted (262); budget_mismatch (186); went_with_competitor (153); timing_conflict (125); contract_terms_disagreement (118); inventory_unavailable (107); campaign_cancelled_internally (96); targeting_mismatch (87); creative_not_ready (11)

lost_leads.loss_reason_detail  (28)
    Quoted rate exceeded client ceiling (111); Client benchmarked against a cheaper media mix (101); Rate card premium on hub screens broke the budget (93); Follow-up emails went unanswered (89); Inquiry appears to have been exploratory only (88); Client stopped responding after initial call (85); Approved budget came in lower than initial ask (64); Client budget was reallocated mid-quarter (62); Indicated budget could not cover requested screen count (60); Competitor offered a bundled multi-city rate (59)

lost_leads.campaign_objective  (4)
    reach (375); awareness (372); frequency (372); conversion (331)

## 1.3 · Map and measure the join graph

Nothing here is inferred from column names. For every declared foreign key we measure:

- **Referential integrity** — share of non-null child keys present in the parent.
- **Fan-out** — max children per parent and max parents per child ⇒ 1:1 / N:1 / N:M.
  A `fanout_trap` is a silent row-multiplier in every later aggregation.
- **Orphans** — child rows joining to nothing. **These are the cold-start population.**

In [13]:
checks = check_all_joins(lake)
joins = joins_frame(checks)
joins[
    [
        "child_table",
        "child_column",
        "parent_table",
        "child_rows",
        "child_null_pct",
        "integrity_pct",
        "orphan_rows",
        "cardinality",
        "max_parents_per_child",
        "fanout_trap",
        "status",
    ]
]

           child_table        child_column        parent_table  child_rows  child_null_pct  integrity_pct  orphan_rows cardinality  max_parents_per_child  fanout_trap status
0    zone_demographics             city_id              cities          30          0.0000            1.0            0         N:1                      1        False     OK
1            locations             city_id              cities         910          0.0000            1.0            0         N:1                      1        False     OK
2            locations             zone_id   zone_demographics         910          0.0000            1.0            0         N:1                      1        False     OK
3          route_stops             city_id              cities        2436          0.0000            1.0            0         N:1                      1        False     OK
4          route_stops         location_id           locations        2436          0.0000            1.0            0         N:1                      1        False     OK
5      route_schedules            route_id         route_stops       19838          0.0000            1.0            0         N:N                     21         True     OK
6    ridership_actuals         schedule_id     route_schedules     2049632          0.0000            1.0            0         N:1                      1        False     OK
7    ridership_actuals             city_id              cities     2049632          0.0000            1.0            0         N:1                      1        False     OK
8             vehicles             city_id              cities         854          0.0000            1.0            0         N:1                      1        False     OK
9             vehicles         corridor_id         route_stops         854          0.0000            1.0            0         N:N                     42         True     OK
10             screens             city_id              cities       11163          0.0000            1.0            0         N:1                      1        False     OK
11             screens         location_id           locations       11163          0.2343            1.0            0         N:1                      1        False     OK
12             screens          vehicle_id            vehicles       11163          0.7657            1.0            0         N:1                      1        False     OK
13  points_of_interest             city_id              cities        1375          0.0000            1.0            0         N:1                      1        False     OK
14  points_of_interest  anchor_location_id           locations        1375          0.0000            1.0            0         N:1                      1        False     OK
15              events             city_id              cities         367          0.0000            1.0            0         N:1                      1        False     OK
16              events              poi_id  points_of_interest         367          0.2343            1.0            0         N:1                      1        False     OK
17              events  anchor_location_id           locations         367          0.0000            1.0            0         N:1                      1        False     OK
18        client_facts        home_city_id              cities         520          0.0000            1.0            0         N:1                      1        False     OK
19            bookings           client_id        client_facts      191109          0.0000            1.0            0         N:1                      1        False     OK
20            bookings             city_id              cities      191109          0.0000            1.0            0         N:1                      1        False     OK
21            bookings           screen_id             screens      191109          0.0000            1.0            0         N:1                      1        False     OK
22            bookings       time_block_id            dim_slot      191109          0.0000            1.0            0         N:1                      1        False     OK
23          lost_leads           client_id        client_facts        1450          0.4434            1.0            0         N:1                      1        False     OK
24          lost_leads             city_id              cities        1450          0.0000            1.0            0         N:1                      1        False     OK
25          lost_leads    anchor_screen_id             screens        1450          0.0000            1.0            0         N:1                      1        False     OK

In [14]:
broken = joins[joins["status"] == "BROKEN"]
if len(broken):
    display(broken[["child_table", "child_column", "parent_table", "integrity_pct", "orphan_rows", "orphan_keys"]])
    for check in checks:
        if check.status == "BROKEN":
            print(f"{check.edge}: example orphan keys -> {list(check.orphan_examples)}")
else:
    print("No edge falls below 99% referential integrity.")

surprising = [c for c in checks if c.unexpected_nulls]
print(f"\nEdges with nulls we did not declare as nullable: {len(surprising)}")
for check in surprising:
    print(f"  {check.edge}: {check.child_null_pct:.1%} null — decide the handling rule.")

No edge falls below 99% referential integrity.

Edges with nulls we did not declare as nullable: 0

In [15]:
# Fan-out traps and the aggregation each consumer must apply before merging.
for check in checks:
    if check.is_fanout_trap:
        print(
            f"{check.edge}\n"
            f"    up to {check.max_parents_per_child:,} parent rows per child key\n"
            f"    -> {check.note or 'aggregate the parent to one row per key before merging'}\n"
        )

route_schedules.route_id -> route_stops.route_id
    up to 21 parent rows per child key
    -> Parent key is non-unique (route_stops is per stop); expect high fan-out.

vehicles.corridor_id -> route_stops.corridor_id
    up to 42 parent rows per child key
    -> Parent key is non-unique; a corridor spans many route_stops rows.

### Key-path resolution

Single-edge integrity is necessary but not sufficient — what matters is whether a
*screen* can be resolved end to end to demographics, to a corridor, to POIs and to
commercial history. Each path below is traced hop by hop.

In [16]:
traces = trace_all_paths(lake, KEY_PATHS)
paths_frame(traces)

,path,start_table,subset,start_rows,resolved_rows,resolution_pct,unresolved_rows,hops,why
0,static geography: screen -> location -> zone -> city,screens,static_screens,8548,8548,1.0000,0,screen -> location → location -> zone → zone -> city,D1 static exposure: resident base and daytime multiplier for a fixed screen.
1,mobile exposure: screen -> vehicle -> corridor,screens,mobile_screens,2615,2615,1.0000,0,screen -> vehicle → vehicle -> corridor stops,D1 mobile exposure: the journey a vehicle-mounted screen travels.
2,ridership: ridership_actuals -> schedule -> route,ridership_actuals,(all rows),2049632,2049632,1.0000,0,actuals -> schedule → schedule -> route stops,Daypart exposure curve per route/corridor.
3,POI context: location -> POI,points_of_interest,(all rows),1375,1375,1.0000,0,POI -> location,"D1 POI pull, distance decay and side-of-road visibility."
4,event context: event -> location/zone,events,(all rows),367,367,1.0000,0,event -> location,Phase 6 event-surge component.
5,commercial history: booking -> screen,bookings,(all rows),191109,191109,1.0000,0,booking -> screen,Pricing training data and committed occupancy per screen.
6,slot claim: booking -> dim_slot,bookings,(all rows),191109,191109,1.0000,0,booking -> time block,How a booking claims inventory in time; defines the sellable unit.
7,client: booking -> client,bookings,(all rows),191109,191109,1.0000,0,booking -> client,Client-relationship adjustment in pricing.
8,pipeline: lead -> client,lost_leads,(all rows),1450,807,0.5566,643,lead -> client,Pipeline pressure and win-probability calibration.

In [17]:
for trace in traces:
    print(f"{trace.path.name}  (start: {trace.start_rows:,} rows)")
    for label, resolved in trace.resolved_at_hop:
        share = resolved / trace.start_rows if trace.start_rows else 0
        print(f"    {label:<28} {resolved:>12,}  ({share:.1%} of start rows)")
    if trace.unresolved_rows:
        print(f"    UNRESOLVED: {trace.unresolved_rows:,} rows -> cold-start population")
    print()

static geography: screen -> location -> zone -> city  (start: 8,548 rows)
    screen -> location                  8,548  (100.0% of start rows)
    location -> zone                    8,548  (100.0% of start rows)
    zone -> city                        8,548  (100.0% of start rows)

mobile exposure: screen -> vehicle -> corridor  (start: 2,615 rows)
    screen -> vehicle                   2,615  (100.0% of start rows)
    vehicle -> corridor stops           2,615  (100.0% of start rows)

ridership: ridership_actuals -> schedule -> route  (start: 2,049,632 rows)
    actuals -> schedule             2,049,632  (100.0% of start rows)
    schedule -> route stops         2,049,632  (100.0% of start rows)

POI context: location -> POI  (start: 1,375 rows)
    POI -> location                     1,375  (100.0% of start rows)

event context: event -> location/zone  (start: 367 rows)
    event -> location                     367  (100.0% of start rows)

commercial history: booking -> screen  (start: 191,109 rows)
    booking -> screen                 191,109  (100.0% of start rows)

slot claim: booking -> dim_slot  (start: 191,109 rows)
    booking -> time block             191,109  (100.0% of start rows)

client: booking -> client  (start: 191,109 rows)
    booking -> client                 191,109  (100.0% of start rows)

pipeline: lead -> client  (start: 1,450 rows)
    lead -> client                        807  (55.7% of start rows)
    UNRESOLVED: 643 rows -> cold-start population

### Static vs mobile split

`screens.location_id` XOR `screens.vehicle_id` decides which D1 exposure model applies.
This is the single most consequential fact in the schema, so it is asserted, not assumed.

In [18]:
screens = lake["screens"]
has_location = screens["location_id"].notna()
has_vehicle = screens["vehicle_id"].notna()

split = pd.DataFrame(
    {
        "screens": [
            int((has_location & ~has_vehicle).sum()),
            int((has_vehicle & ~has_location).sum()),
            int((has_location & has_vehicle).sum()),
            int((~has_location & ~has_vehicle).sum()),
        ]
    },
    index=["static (location only)", "mobile (vehicle only)", "BOTH — ambiguous", "NEITHER — orphan"],
)
split["share"] = (split["screens"] / len(screens)).map("{:.1%}".format)
display(split)

assert (has_location ^ has_vehicle).all(), (
    "location_id XOR vehicle_id does not hold — the static/mobile exposure split needs a rule."
)
print("XOR holds: every screen is unambiguously static or mobile.")

display(
    pd.crosstab(screens["screen_type"], has_vehicle.map({True: "mobile", False: "static"}))
)

                        screens  share
static (location only)     8548  76.6%
mobile (vehicle only)      2615  23.4%
BOTH — ambiguous              0   0.0%
NEITHER — orphan              0   0.0%

XOR holds: every screen is unambiguously static or mobile.

vehicle_id        mobile  static
screen_type
bus                 1215       0
bus_stop               0    2157
metro_rail_coach    1400       0
metro_station          0    6391

### ER diagram (measured)

Cardinality and integrity % come from the measurements above. This diagram is reused
directly in the Phase 2 C4 component view.

In [19]:
from IPython.display import Markdown

Markdown("```mermaid\n" + mermaid_er(checks) + "\n```")

```mermaid
erDiagram
    cities ||--|{ zone_demographics : "city_id 100%"
    cities ||--|{ locations : "city_id 100%"
    zone_demographics ||--|{ locations : "zone_id 100%"
    cities ||--|{ route_stops : "city_id 100%"
    locations ||--|{ route_stops : "location_id 100%"
    route_stops }o--|{ route_schedules : "route_id 100%"
    route_schedules ||--|{ ridership_actuals : "schedule_id 100%"
    cities ||--|{ ridership_actuals : "city_id 100%"
    cities ||--|{ vehicles : "city_id 100%"
    route_stops }o--|{ vehicles : "corridor_id 100%"
    cities ||--|{ screens : "city_id 100%"
    locations ||--o{ screens : "location_id 100%"
    vehicles ||--o{ screens : "vehicle_id 100%"
    cities ||--|{ points_of_interest : "city_id 100%"
    locations ||--|{ points_of_interest : "anchor_location_id 100%"
    cities ||--|{ events : "city_id 100%"
    points_of_interest ||--o{ events : "poi_id 100%"
    locations ||--o{ events : "anchor_location_id 100%"
    cities ||--|{ client_facts : "home_city_id 100%"
    client_facts ||--|{ bookings : "client_id 100%"
    cities ||--|{ bookings : "city_id 100%"
    screens ||--|{ bookings : "screen_id 100%"
    dim_slot ||--|{ bookings : "time_block_id 100%"
    client_facts ||--o{ lost_leads : "client_id 100%"
    cities ||--|{ lost_leads : "city_id 100%"
    screens ||--o{ lost_leads : "anchor_screen_id 100%"
```

## Integration check — one wide screen view

Proof that the graph actually composes: every screen, joined to its geography,
demographics, corridor, POI context and commercial history, with **fan-out traps
aggregated rather than merged**. This frame is the input contract for Phase 3.

In [20]:
locations = lake["locations"]
zones = lake["zone_demographics"]
cities = lake["cities"]
vehicles = lake["vehicles"]
pois = lake["points_of_interest"]
bookings = lake["bookings"]

# --- static geography -------------------------------------------------------
screen_view = (
    screens.merge(
        locations[["location_id", "zone_id", "city_zone", "location_type"]],
        on="location_id",
        how="left",
    )
    .merge(
        zones[["zone_id", "zone_name", "resident_population", "income_index", "daytime_population_multiplier"]],
        on="zone_id",
        how="left",
    )
    .merge(cities[["city_id", "city_name", "market_tier", "timezone"]], on="city_id", how="left")
    .merge(vehicles[["vehicle_id", "vehicle_type", "corridor_id"]], on="vehicle_id", how="left")
)

# --- POI context: aggregate first, then merge (fan-out trap) ----------------
poi_context = pois.groupby("anchor_location_id", observed=True).agg(
    poi_count=("poi_id", "count"),
    poi_footfall_total=("est_daily_footfall", "sum"),
    poi_nearest_km=("distance_to_location_km", "min"),
)
screen_view = screen_view.merge(
    poi_context, left_on="location_id", right_index=True, how="left"
)

# --- commercial history: aggregate first, then merge (fan-out trap) ---------
booking_history = bookings.groupby("screen_id", observed=True).agg(
    bookings=("booking_id", "count"),
    revenue=("line_item_value", "sum"),
    median_price_per_slot_day=("contracted_price_per_slot_per_day", "median"),
    first_booking=("start_date", "min"),
    last_booking=("end_date", "max"),
)
screen_view = screen_view.merge(
    booking_history, left_on="screen_id", right_index=True, how="left"
)
screen_view["bookings"] = screen_view["bookings"].fillna(0).astype(int)

assert len(screen_view) == len(screens), (
    f"row multiplication: {len(screens):,} screens became {len(screen_view):,} rows"
)
print(f"screen_view: {len(screen_view):,} rows x {screen_view.shape[1]} cols — no row multiplication.")
screen_view.head(3)

screen_view: 11,163 rows x 27 cols — no row multiplication.

,screen_id,city_id,screen_type,location_id,vehicle_id,position,screen_size,zone_id,city_zone,location_type,zone_name,resident_population,income_index,daytime_population_multiplier,city_name,market_tier,timezone,vehicle_type,corridor_id,poi_count,poi_footfall_total,poi_nearest_km,bookings,revenue,median_price_per_slot_day,first_booking,last_booking
0,LH-SCR-000001,LH,bus_stop,LH-LOC-0120,NaN,top,M,LH-ZONE-005,Financial Row,bus_stop,Financial Row,202967.0,159.8,3.21,Las Hackland,premium,America/New_York,NaN,NaN,1.0,29380.0,0.384,13,195060.03,87.10,2025-08-31,2027-02-01
1,LH-SCR-000002,LH,bus_stop,LH-LOC-0120,NaN,left,S,LH-ZONE-005,Financial Row,bus_stop,Financial Row,202967.0,159.8,3.21,Las Hackland,premium,America/New_York,NaN,NaN,1.0,29380.0,0.384,11,137461.92,78.94,2025-08-28,2027-01-15
2,LH-SCR-000003,LH,bus_stop,LH-LOC-0120,NaN,right,S,LH-ZONE-005,Financial Row,bus_stop,Financial Row,202967.0,159.8,3.21,Las Hackland,premium,America/New_York,NaN,NaN,1.0,29380.0,0.384,12,153650.17,77.80,2025-09-19,2027-02-19

In [21]:
# Coverage of each downstream signal — a preview of the Step 1.7 cold-start census.
coverage = pd.DataFrame(
    {
        "screens": [
            len(screen_view),
            int(screen_view["zone_id"].notna().sum()),
            int(screen_view["corridor_id"].notna().sum()),
            int(screen_view["poi_count"].notna().sum()),
            int((screen_view["bookings"] > 0).sum()),
            int((screen_view["bookings"] == 0).sum()),
        ]
    },
    index=[
        "total",
        "resolved to a zone (demographics available)",
        "resolved to a corridor (mobile exposure available)",
        "has nearby POI context",
        "has booking history (priceable from own history)",
        "ZERO bookings -> needs the fallback ladder",
    ],
)
coverage["share"] = (coverage["screens"] / len(screen_view)).map("{:.1%}".format)
coverage

                                                    screens   share
total                                                 11163  100.0%
resolved to a zone (demographics available)            8548   76.6%
resolved to a corridor (mobile exposure available)     2615   23.4%
has nearby POI context                                 8548   76.6%
has booking history (priceable from own history)       9939   89.0%
ZERO bookings -> needs the fallback ladder             1224   11.0%

In [22]:
# Persist the integrated view so Steps 1.4-1.7 and Phase 3 do not rebuild these joins.
artifact = PATHS.artifacts / "screen_view.parquet"
try:
    screen_view.to_parquet(artifact, index=False)
    print(f"wrote {artifact.relative_to(ROOT)}  ({artifact.stat().st_size / 1024**2:.1f} MB)")
except ImportError:
    fallback = artifact.with_suffix(".csv")
    screen_view.to_csv(fallback, index=False)
    print(f"pyarrow not installed; wrote {fallback.relative_to(ROOT)} instead")

wrote data\artifacts\screen_view.parquet  (0.3 MB)

## Campaign brief integration

The other half of the input surface. Each `.docx` is parsed **deterministically** — a
`.docx` is a zip holding `word/document.xml`, so no LLM and no heavy dependency is
involved. Two layers:

1. **Structure** (`parse_brief`) — title, header label/value pairs, numbered sections,
   RFP requirement list. Lossless: every paragraph lands somewhere or is reported.
2. **Normalisation** (`derive_fields`) — budget, duration, age band, slot request.

These become the **gold parses** that the Phase 4 LLM extractor is tested against, which
is exactly why they are produced by regex rather than by a model.

In [23]:
briefs = load_briefs(PATHS.campaigns)
print(f"{len(briefs)} brief documents parsed from {PATHS.campaigns.name}/\n")

brief_table = briefs_frame(briefs)
brief_table

6 brief documents parsed from Campaigns/

,brief,source_file,campaign,company,industry_vertical,objective,target_audience,budget_amount,duration_days,age_min,age_max,slots_requested,seconds_per_minute,n_location_requirements,n_exclusions,n_rfp_requirements,n_unresolved
0,1,campaign_1.docx,ZEPHYR EV — THE FUTURE HAS NO TAILPIPE,Voltaic Motors Inc. (Brand: Zephyr EV),AUTOMOTIVE / ELECTRIC VEHICLES,Brand Awareness & Test-Drive Bookings,Urban professionals and eco-conscious upgraders (Ages 28-50),40000.0,45,28,50,1.0,15.0,2,1,3,6
1,2,campaign_2.docx,EMBER ENERGY — IGNITE EVERY HOUR,Ember Beverages LLC,FMCG / BEVERAGES (ENERGY DRINKS),Trial & Impulse Purchase,"Gen Z and young professionals, gym-goers, night-shift workers (Ages 18-30)",12000.0,21,18,30,NaN,NaN,4,0,3,2
2,3,campaign_3.docx,LOOM & THREAD — WEAR YOUR STORY,Loom & Thread Apparel Co.,RETAIL / FASHION,Seasonal Footfall & Sale Awareness,Style-conscious shoppers (Ages 20-40),22000.0,20,20,40,NaN,NaN,3,0,3,3
3,4,campaign_4.docx,"BASIL & BLOOM — FRESH, FAST, FLAVORFUL",Basil & Bloom Fast-Casual Kitchens,FOOD & BEVERAGE / QSR,Lunch-Hour Footfall & Local Recall,Office workers and students (Ages 18-35),9000.0,15,18,35,NaN,NaN,2,1,3,4
4,5,campaign_5.docx,"SKYNIMBUS AIRLINES — FLY FURTHER, FEEL CLOSER",SkyNimbus Airlines Ltd.,TRAVEL & AVIATION,New Route Awareness & Bookings,"Frequent flyers, business and leisure travelers (Ages 28-55)",35000.0,40,28,55,NaN,NaN,3,0,3,3
5,6,campaign_6.docx,LUMIÈRE COSMETICS — GLOW ON YOUR TERMS,Lumière Cosmetics Group,BEAUTY & PERSONAL CARE,New Product Launch Awareness,"Young women, beauty-conscious commuters (Ages 18-34)",20000.0,25,18,34,NaN,NaN,3,0,3,2

In [24]:
# Which header fields is every brief guaranteed to state? -> which are required in the schema.
coverage_briefs = coverage_frame(briefs)
display(coverage_briefs)

always = [c for c in coverage_briefs.columns if coverage_briefs[c].dtype == bool and coverage_briefs[c].all()]
sometimes = [
    c
    for c in coverage_briefs.columns
    if coverage_briefs[c].dtype == bool and not coverage_briefs[c].all()
]
print(f"REQUIRED in CampaignBrief (present in all briefs): {always}")
print(f"OPTIONAL (missing in at least one):                {sometimes}")
print(f"Unparsed paragraphs (should be ~0): {coverage_briefs['unparsed_paragraphs'].sum()}")

   brief      source_file  sections  unparsed_paragraphs  Company Name  Industry Vertical  Campaign Objective  Target Audience  Campaign Budget  Campaign Duration
0      1  campaign_1.docx         5                    2          True               True                True             True             True               True
1      2  campaign_2.docx         5                    0          True               True                True             True             True               True
2      3  campaign_3.docx         5                    0          True               True                True             True             True               True
3      4  campaign_4.docx         5                    0          True               True                True             True             True               True
4      5  campaign_5.docx         5                    0          True               True                True             True             True               True
5      6  campaign_6.docx         5                    0          True               True                True             True             True               True

REQUIRED in CampaignBrief (present in all briefs): ['Company Name', 'Industry Vertical', 'Campaign Objective', 'Target Audience', 'Campaign Budget', 'Campaign Duration']
OPTIONAL (missing in at least one):                []
Unparsed paragraphs (should be ~0): 2

In [25]:
# Hard constraints vs soft preferences, per brief.
for brief in briefs:
    fields = derive_fields(brief)
    print(f"\n{'=' * 100}\nBRIEF {fields.brief_number}: {fields.campaign_title}")
    print(f"  company     {fields.company}  |  vertical {fields.industry_vertical}")
    print(f"  objective   {fields.objective}")
    print(f"  audience    {fields.target_audience}  (ages {fields.age_min}-{fields.age_max})")
    print(f"  budget      {fields.budget_amount:,.0f}" if fields.budget_amount else "  budget      —")
    print(f"  duration    {fields.duration_days} days")
    print(f"  slots       {fields.slots_requested} slot(s), {fields.seconds_per_minute}s per minute")
    print("  HARD exclusions:")
    for exclusion in fields.exclusions or ["(none stated)"]:
        print(f"    - {exclusion}")
    print("  Location / environment requirements:")
    for requirement in fields.location_requirements or ["(none stated)"]:
        print(f"    - {requirement}")
    print("  Capabilities this brief demands:")
    for unresolved in fields.unresolved_requirements or ["(none flagged)"]:
        print(f"    ! {unresolved}")

====================================================================================================
BRIEF 1: ZEPHYR EV — THE FUTURE HAS NO TAILPIPE
  company     Voltaic Motors Inc. (Brand: Zephyr EV)  |  vertical AUTOMOTIVE / ELECTRIC VEHICLES
  objective   Brand Awareness & Test-Drive Bookings
  audience    Urban professionals and eco-conscious upgraders (Ages 28-50)  (ages 28-50)
  budget      40,000
  duration    45 days
  slots       1 slot(s), 15s per minute
  HARD exclusions:
    - Exclude bus-rear screens and value-tier inventory in high-density residential areas — the campaign is intentionally not mass-market and should avoid diluting the premium positioning.
  Location / environment requirements:
    - High-Dwell Business-District Platforms: Metro platform boards in the city's primary commercial and financial districts, where affluent professional commuters typically spend three to six minutes waiting on the platform.
    - Auto-Retail Arterial Corridors: Roadside-adjacent transit screens on major arterial routes with a dense concentration of car dealerships, positioned to intercept shoppers already actively comparing vehicles.
  Capabilities this brief demands:
    ! dwell-time reasoning — needs interior/exterior and location-type exposure model
    ! creative aspect-ratio restriction — needs a screen format attribute
    ! format restriction to digital inventory — needs a screen format attribute
    ! QR / response-mechanic tracking — affects objective fit, not inventory
    ! premium-tier positioning — maps to market_tier and price band
    ! hard exclusion — must be enforced in the Phase 5 eligibility filter

====================================================================================================
BRIEF 2: EMBER ENERGY — IGNITE EVERY HOUR
  company     Ember Beverages LLC  |  vertical FMCG / BEVERAGES (ENERGY DRINKS)
  objective   Trial & Impulse Purchase
  audience    Gen Z and young professionals, gym-goers, night-shift workers (Ages 18-30)  (ages 18-30)
  budget      12,000
  duration    21 days
  slots       None slot(s), Nones per minute
  HARD exclusions:
    - (none stated)
  Location / environment requirements:
    - Nightlife and Entertainment Corridors: Bus rear screens on routes running through late-night entertainment districts, positioned to catch post-venue crowds heading home.
    - Campus-Edge Transit Nodes: Screens at transit nodes serving large student populations, timed to exam-season late-study patterns.
    - Event-Venue Precincts: Digital boards near major stadium and arena precincts, where footfall spikes sharply on event nights.
    - Time-of-Day Target: Heavy weighting on late evening through early morning rather than standard commute peaks.
  Capabilities this brief demands:
    ! QR / response-mechanic tracking — affects objective fit, not inventory
    ! effective-frequency requirement — needs the reach/frequency split (Step 3.5)

====================================================================================================
BRIEF 3: LOOM & THREAD — WEAR YOUR STORY
  company     Loom & Thread Apparel Co.  |  vertical RETAIL / FASHION
  objective   Seasonal Footfall & Sale Awareness
  audience    Style-conscious shoppers (Ages 20-40)  (ages 20-40)
  budget      22,000
  duration    20 days
  slots       None slot(s), Nones per minute
  HARD exclusions:
    - (none stated)
  Location / environment requirements:
    - Premium Mall Entry Points: High-footfall digital boards at the entrances of the network's largest shopping centres, where shoppers arrive with purchase intent already formed.
    - High-Street Retail Corridors: Screens along established high-street shopping strips with a concentration of competing apparel retailers.
    - Weekend Weighting: Requesting weighted delivery from Friday evening through Sunday, aligned with peak discretionary shopping behaviour.
  Capabilities this brief demands:
    ! weekend vs weekday weighting — needs day-type split in the daypart curve
    ! weekday weighting — needs day-type split in the daypart curve
    ! premium-tier positioning — maps to market_tier and price band

====================================================================================================
BRIEF 4: BASIL & BLOOM — FRESH, FAST, FLAVORFUL
  company     Basil & Bloom Fast-Casual Kitchens  |  vertical FOOD & BEVERAGE / QSR
  objective   Lunch-Hour Footfall & Local Recall
  audience    Office workers and students (Ages 18-35)  (ages 18-35)
  budget      9,000
  duration    15 days
  slots       None slot(s), Nones per minute
  HARD exclusions:
    - Exclude all nodes outside a realistic walking distance of the outlet. Reach beyond that radius is wasted spend for a single-location launch.
  Location / environment requirements:
    - Immediate Walking Radius of the New Outlet: Screens within a short walking distance of a single new outlet located in a business-park food court — the campaign's entire reach requirement sits inside that radius.
    - Midday Commercial-District Coverage: Screens in the surrounding commercial district, weighted specifically to the lunch window.
  Capabilities this brief demands:
    ! walking-radius / distance constraint — needs the POI proximity rule (Step 1.6)
    ! explicit radius constraint — needs the POI proximity rule (Step 1.6)
    ! creative aspect-ratio restriction — needs a screen format attribute
    ! hard exclusion — must be enforced in the Phase 5 eligibility filter

====================================================================================================
BRIEF 5: SKYNIMBUS AIRLINES — FLY FURTHER, FEEL CLOSER
  company     SkyNimbus Airlines Ltd.  |  vertical TRAVEL & AVIATION
  objective   New Route Awareness & Bookings
  audience    Frequent flyers, business and leisure travelers (Ages 28-55)  (ages 28-55)
  budget      35,000
  duration    40 days
  slots       None slot(s), Nones per minute
  HARD exclusions:
    - (none stated)
  Location / environment requirements:
    - Airport Transit Corridor: Premium wide-format screens along the primary airport access corridor — the single highest-relevance environment for a travel campaign, reaching an audience already in a travel mindset.
    - Premium Business Core: Screens across the city's premium commercial core, reaching frequent business travellers on their daily commute.
    - Financial District Coverage: Supplementary placement at major financial-district metro nodes for repeated business-traveller exposure across the campaign window.
  Capabilities this brief demands:
    ! creative aspect-ratio restriction — needs a screen format attribute
    ! effective-frequency requirement — needs the reach/frequency split (Step 3.5)
    ! premium-tier positioning — maps to market_tier and price band

====================================================================================================
BRIEF 6: LUMIÈRE COSMETICS — GLOW ON YOUR TERMS
  company     Lumière Cosmetics Group  |  vertical BEAUTY & PERSONAL CARE
  objective   New Product Launch Awareness
  audience    Young women, beauty-conscious commuters (Ages 18-34)  (ages 18-34)
  budget      20,000
  duration    25 days
  slots       None slot(s), Nones per minute
  HARD exclusions:
    - (none stated)
  Location / environment requirements:
    - Mall Beauty-Retail Entry: Premium vertical screens at shopping centre entrances adjacent to beauty and lifestyle retail concessions, reaching shoppers moments before they pass a beauty counter.
    - High-Street Retail Corridors: Vertical screens along high-street shopping strips with a concentration of competing beauty retailers.
    - Central Metro Entry Coverage: Supplementary vertical placements at central metro entry points, for repeated commuter exposure ahead of weekend shopping trips.
  Capabilities this brief demands:
    ! weekend vs weekday weighting — needs day-type split in the daypart curve
    ! premium-tier positioning — maps to market_tier and price band

In [26]:
# The stated RFP deliverables — this table becomes the Phase 8 acceptance checklist.
requirements_frame(briefs)

    brief      source_file                                       campaign  requirement_no                                                                                requirement
0       1  campaign_1.docx         ZEPHYR EV — THE FUTURE HAS NO TAILPIPE               1  A curated shortlist of screens across the premium business-district platforms and auto...
1       1  campaign_1.docx         ZEPHYR EV — THE FUTURE HAS NO TAILPIPE               2  An optimal price recommendation reflecting premium-node demand, platform dwell time, a...
2       1  campaign_1.docx         ZEPHYR EV — THE FUTURE HAS NO TAILPIPE               3  Projected weekly impressions and test-drive-booking potential, with logical justificat...
3       2  campaign_2.docx               EMBER ENERGY — IGNITE EVERY HOUR               1  An inventory package combining bus-rear screens on nightlife corridors with campus-edg...
4       2  campaign_2.docx               EMBER ENERGY — IGNITE EVERY HOUR               2  Dynamic pricing reflecting late-night demand patterns and event-night surge behaviour ...
5       2  campaign_2.docx               EMBER ENERGY — IGNITE EVERY HOUR               3  A reach plan optimised for unique late-night impressions within the stated budget, pri...
6       3  campaign_3.docx                LOOM & THREAD — WEAR YOUR STORY               1  An inventory plan anchored on premium mall entry points and high-street retail corridors.
7       3  campaign_3.docx                LOOM & THREAD — WEAR YOUR STORY               2           Pricing reflecting weekend-weighted delivery and premium mall-entry positioning.
8       3  campaign_3.docx                LOOM & THREAD — WEAR YOUR STORY               3  A footfall-oriented reach projection for the 20-day sale window, with the weekend-vers...
9       4  campaign_4.docx         BASIL & BLOOM — FRESH, FAST, FLAVORFUL               1  A tightly-scoped inventory list limited to screens within realistic walking distance o...
10      4  campaign_4.docx         BASIL & BLOOM — FRESH, FAST, FLAVORFUL               2                      Pricing reflecting the hyper-local, midday-weighted delivery pattern.
11      4  campaign_4.docx         BASIL & BLOOM — FRESH, FAST, FLAVORFUL               3  A footfall-conversion-oriented reach estimate for the 15-day launch window, explicitly...
12      5  campaign_5.docx  SKYNIMBUS AIRLINES — FLY FURTHER, FEEL CLOSER               1  A curated list of screens anchored on the airport transit corridor and the premium bus...
13      5  campaign_5.docx  SKYNIMBUS AIRLINES — FLY FURTHER, FEEL CLOSER               2  Pricing reflecting premium-corridor demand and the overlap between the business and le...
14      5  campaign_5.docx  SKYNIMBUS AIRLINES — FLY FURTHER, FEEL CLOSER               3  Projected reach across the 40-day window, with separate estimates for repeat business-...
15      6  campaign_6.docx         LUMIÈRE COSMETICS — GLOW ON YOUR TERMS               1  An inventory plan anchored on mall beauty-retail entry points and high-street retail c...
16      6  campaign_6.docx         LUMIÈRE COSMETICS — GLOW ON YOUR TERMS               2  Pricing reflecting premium mall-entry positioning and the value of beauty-retail adjac...
17      6  campaign_6.docx         LUMIÈRE COSMETICS — GLOW ON YOUR TERMS               3  A projected reach estimate for the 25-day window, with reasoning tied to beauty-audien...

### Do the briefs' vocabulary and the data's vocabulary agree?

The first real integration test between the two input sources. A brief's industry
vertical must land on a value that actually exists in `bookings.industry_vertical` /
`client_facts.industry`, and its objective on a real `campaign_objective` — otherwise
Phase 4's resolution step has nothing to bind to.

In [27]:
data_verticals = sorted(
    set(bookings["industry_vertical"].astype(str).unique())
    | set(lake["client_facts"]["industry"].astype(str).unique())
)
data_objectives = sorted(bookings["campaign_objective"].astype(str).unique())

print(f"data verticals ({len(data_verticals)}): {data_verticals}")
print(f"data objectives ({len(data_objectives)}): {data_objectives}\n")


def _bind(candidates: list[str], text: str) -> list[str]:
    """Exact-token or prefix match only. Anything looser belongs in taxonomy.yaml."""
    words = set(re.findall(r"[a-z]+", text.lower()))
    return [
        value
        for value in candidates
        if value in words or any(word.startswith(value) for word in words)
    ]


rows = []
for brief in briefs:
    fields = derive_fields(brief)
    rows.append(
        {
            "brief": fields.brief_number,
            "brief_vertical": fields.industry_vertical,
            "vertical_binds_to": _bind(data_verticals, fields.industry_vertical),
            "brief_objective": fields.objective,
            "objective_binds_to": _bind(data_objectives, fields.objective),
        }
    )

mapping = pd.DataFrame(rows)
display(mapping)

unbound_v = mapping.loc[mapping["vertical_binds_to"].str.len() == 0, "brief_vertical"].tolist()
unbound_o = mapping.loc[mapping["objective_binds_to"].str.len() == 0, "brief_objective"].tolist()
print(f"Verticals with no binding ({len(unbound_v)}): {unbound_v}")
print(f"Objectives with no binding ({len(unbound_o)}): {unbound_o}")
print(
    "\nThese are the finding, not a bug: each unbound value is a synonym\n"
    "config/taxonomy.yaml must supply before Step 4.2 can resolve a brief."
)

data verticals (13): ['auto', 'cpg', 'education', 'entertainment', 'finance', 'government', 'healthcare', 'hospitality', 'nonprofit', 'real_estate', 'retail', 'technology', 'telecom']
data objectives (4): ['awareness', 'conversion', 'frequency', 'reach']

   brief                    brief_vertical vertical_binds_to                        brief_objective objective_binds_to
0      1    AUTOMOTIVE / ELECTRIC VEHICLES            [auto]  Brand Awareness & Test-Drive Bookings        [awareness]
1      2  FMCG / BEVERAGES (ENERGY DRINKS)                []               Trial & Impulse Purchase                 []
2      3                  RETAIL / FASHION          [retail]     Seasonal Footfall & Sale Awareness        [awareness]
3      4             FOOD & BEVERAGE / QSR                []     Lunch-Hour Footfall & Local Recall                 []
4      5                 TRAVEL & AVIATION                []         New Route Awareness & Bookings        [awareness]
5      6            BEAUTY & PERSONAL CARE                []           New Product Launch Awareness        [awareness]

Verticals with no binding (4): ['FMCG / BEVERAGES (ENERGY DRINKS)', 'FOOD & BEVERAGE / QSR', 'TRAVEL & AVIATION', 'BEAUTY & PERSONAL CARE']
Objectives with no binding (2): ['Trial & Impulse Purchase', 'Lunch-Hour Footfall & Local Recall']

These are the finding, not a bug: each unbound value is a synonym
config/taxonomy.yaml must supply before Step 4.2 can resolve a brief.

## Generate `docs/data_dictionary.md`

Steps 1.2 and 1.3 land in one committed, regenerable document.

In [28]:
from datetime import datetime, timezone

join_section = render_join_section(checks, traces)
dictionary = render_data_dictionary(
    profiles,
    join_section=join_section,
    generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
)

target = PATHS.docs / "data_dictionary.md"
target.write_text(dictionary, encoding="utf-8")
print(f"wrote {target.relative_to(ROOT)}  ({len(dictionary):,} chars)")

wrote docs\data_dictionary.md  (49,167 chars)

## Phase 1.1–1.3 exit checklist

Run the cell below. Anything printed as `FAIL` blocks Step 1.4.

In [29]:
gates = {
    "1.1 all 14 tables load with zero parse errors": len(inventory) == 14 and (inventory["rows"] > 0).all(),
    "1.2 every declared primary key is unique": bool((table_summary["pk_unique"] != False).all()),  # noqa: E712
    "1.2 every column profiled": len(columns) == int(inventory["columns"].sum()),
    "1.2 every column has a stated meaning": len(todo) == 0,
    "1.2 data dictionary written": target.is_file(),
    "1.3 every declared edge measured": len(joins) > 0 and joins["integrity_pct"].notna().all(),
    "1.3 no edge below 99% integrity": bool((joins["integrity_pct"] >= 0.99).all()),
    "1.3 fan-out traps documented": all(
        check.note for check in checks if check.is_fanout_trap
    ),
    "1.3 screens integrate without row multiplication": len(screen_view) == len(screens),
    "+   all 6 briefs parsed with a budget": len(briefs) == 6 and bool(brief_table["budget_amount"].notna().all()),
    "+   every brief yields its RFP deliverables": bool(brief_table["n_rfp_requirements"].gt(0).all()),
    "+   every brief states all 6 header fields": bool(
        coverage_briefs[list(coverage_briefs.select_dtypes("bool").columns)].all().all()
    ),
}

width = max(len(name) for name in gates)
for name, passed in gates.items():
    print(f"{'PASS' if passed else 'FAIL'}  {name:<{width}}")

open_items = sum(1 for passed in gates.values() if not passed)
print(f"\n{len(gates) - open_items}/{len(gates)} gates passed.")
if len(todo):
    print(f"Carry-forward: {len(todo)} columns still marked #TODO-semantics (resolve before Phase 3).")

PASS  1.1 all 14 tables load with zero parse errors
PASS  1.2 every declared primary key is unique
PASS  1.2 every column profiled
PASS  1.2 every column has a stated meaning
PASS  1.2 data dictionary written
PASS  1.3 every declared edge measured
PASS  1.3 no edge below 99% integrity
PASS  1.3 fan-out traps documented
PASS  1.3 screens integrate without row multiplication
PASS  +   all 6 briefs parsed with a budget
PASS  +   every brief yields its RFP deliverables
PASS  +   every brief states all 6 header fields

12/12 gates passed.

## What Step 1.4 inherits from here

| Artifact | Used by |
| --- | --- |
| `DataLake` (+ parquet cache) | every later notebook and engine — no reloading logic gets rewritten |
| `docs/data_dictionary.md` | cited by Phases 3–7 as the schema source of truth |
| `data/artifacts/screen_view.parquet` | Step 1.4 inventory shape, Phase 3 exposure models |
| measured `JoinCheck`s | the required aggregation before any merge |
| `KEY_PATHS` traces | cold-start sizing (Step 1.7), fallback-ladder design (Step 6.5) |
| gold brief parses | Phase 4 extractor test fixtures |
| RFP requirement table | Phase 8 acceptance criteria |

**Next (Step 1.4)** — profile the inventory: screens by city / type / position / size,
and the exact sellable-unit count (screens × time blocks × rotation slots × days), which
the Phase 7 solver design must cite.